In [1]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [2]:
A = np.array([[1, 0, 1],
              [2, 5**.5, 0],
              [0, 0, 1],
              [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A.T)
print(B)


[[-2.23606798e+00  1.11022302e-16  0.00000000e+00  0.00000000e+00]
 [ 2.04939015e+00  8.39500986e-01 -2.67014343e-18 -4.39009789e-18]
 [-9.45175510e-17 -5.07346289e-01  1.68458833e+00 -3.33066907e-16]]


In [3]:
P.shape

(4, 4)

In [4]:
Qt @ A.T @ P[:, :3]

array([[-2.23606798e+00, -1.11022302e-16,  5.55111512e-17],
       [ 2.04939015e+00,  8.39500986e-01, -5.55111512e-17],
       [ 1.11022302e-16, -5.07346289e-01,  1.68458833e+00]])

Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II-A

In [5]:
scipy.linalg.eigh(B.T@B)

(array([2.18034422e-47, 3.36223240e-01, 3.11464321e+00, 9.54913355e+00]),
 array([[ 0.00000000e+00,  1.80654708e-01, -8.67828811e-02,
          9.79710471e-01],
        [ 5.22941363e-18, -9.30726841e-01,  3.06954677e-01,
          1.98812407e-01],
        [ 1.99289064e-16, -3.17980225e-01, -9.47759230e-01,
         -2.53183491e-02],
        [ 1.00000000e+00,  6.82371370e-17,  1.87272857e-16,
          4.00599778e-18]]))

**Test SVD**

In [6]:
%precision 8

'%.8f'

In [33]:
SVD.svd(A)

(array([[-0.26444298,  0.60575682, -0.75041894],
        [-0.96312812, -0.2058522 ,  0.17323137],
        [-0.03502958,  0.54345356,  0.45103343],
        [-0.03502958,  0.54345356,  0.45103343]]),
 array([3.09016724, 1.76483518, 0.5798476 ]),
 array([[ 0.70892578,  0.69692666,  0.10824726],
        [ 0.10995498, -0.26081728,  0.95910596],
        [-0.69665927,  0.66803262,  0.26153065]]))

In [ ]:
scipy.linalg.svd(A, full_matrices=False)

(array([[-0.26444298,  0.60575682,  0.75041894],
        [-0.96312812, -0.2058522 , -0.17323137],
        [-0.03502958,  0.54345356, -0.45103343],
        [-0.03502958,  0.54345356, -0.45103343]]),
 array([3.09016724, 1.76483518, 0.5798476 ]),
 array([[-0.70892578, -0.69692666, -0.10824726],
        [ 0.10995498, -0.26081728,  0.95910596],
        [ 0.69665927, -0.66803262, -0.26153065]]))