In [1]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [2]:
%precision 8

'%.8f'

In [3]:
A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0],
              [2, 5, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]], dtype=np.float64)


# A = np.array([[1, 0, 1],
#               [2, 5**.5, 0],
#               [0, 0, 1],
#               [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[ 2. -5.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [4]:
print(Qt @ A @ P)

[[ 2. -5.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II-A

**Test SVD**

In [5]:
%precision 4

'%.4f'

In [6]:
U, S, Vt = SVD.svd(A)
print(U@np.diag(S)@Vt)
print(np.abs(U@np.diag(S)@Vt - A)< 1e-15)
U, S, Vt

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [2. 5. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


(array([[0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]]),
 array([5.3852, 1.    ]),
 array([[0.3714, 0.9285, 0.    , 0.    ],
        [0.    , 0.    , 1.    , 0.    ]]))

In [7]:
U, S, Vt  = scipy.linalg.svd(A, full_matrices=False)
print(U@np.diag(S)@Vt)
U, S, Vt

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 0.]
 [2. 5. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


(array([[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.],
        [ 0.,  1.,  0.,  0.],
        [ 0.,  0.,  1.,  0.],
        [-1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]),
 array([5.3852, 1.    , 0.    , 0.    ]),
 array([[-0.3714, -0.9285, -0.    , -0.    ],
        [ 0.    ,  0.    ,  1.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    ,  1.    ],
        [-0.9285,  0.3714,  0.    ,  0.    ]]))

In [8]:
np.abs(U @ np.diag(S) @ Vt - A) < 1e-15

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])