In [51]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [52]:
%precision 8

'%.8f'

In [53]:
A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0],
              [2, 5, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]], dtype=np.float64)


# A = np.array([[1, 0, 1],
#               [2, 5**.5, 0],
#               [0, 0, 1],
#               [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[ 2. -5.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [54]:
print(Qt @ A @ P)

[[ 2. -5.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II-A

**Test SVD**

In [55]:
%precision 4

'%.4f'

In [59]:
m=  n = 500
A = np.random.rand(m,n)
A[400:, :] = 0

In [60]:
U, S, Vt = SVD.svd(A)
acc = 1e-13
print("Percentage of entrices successfully recovered by SVD with accuracy: {}".format(acc))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< acc) / (n*m) * 100, "%")
U, S, Vt

phaseI: 2.2442007064819336
phaseII: 5.526231527328491
Percentage of entrices successfully recovered by SVD with accuracy: 1e-13
100.0 %


(array([[-0.0509, -0.0464, -0.0464, ...,  0.0708,  0.0389, -0.061 ],
        [-0.0495, -0.0178,  0.0671, ..., -0.0344, -0.0974,  0.0345],
        [-0.0519,  0.0548, -0.0614, ...,  0.0799, -0.0191, -0.0645],
        ...,
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ],
        [ 0.    ,  0.    ,  0.    , ...,  0.    ,  0.    ,  0.    ]]),
 array([223.6572,  12.1644,  11.9893,  11.9116,  11.8224,  11.7723,
         11.6716,  11.5461,  11.5303,  11.4679,  11.3899,  11.3294,
         11.2637,  11.2179,  11.1585,  11.1   ,  11.0453,  11.0126,
         10.9896,  10.8977,  10.8784,  10.858 ,  10.8119,  10.7737,
         10.6332,  10.6096,  10.5753,  10.537 ,  10.5034,  10.4648,
         10.4098,  10.337 ,  10.301 ,  10.2873,  10.2034,  10.1935,
         10.1339,  10.1039,  10.0775,  10.0689,  10.0079,   9.9512,
          9.9212,   9.8706,   9.8223,   9.7923,   9.7553,   9.749 ,
          9.711 ,   9.659 ,

In [58]:
U, S, Vt  = scipy.linalg.svd(A, full_matrices=False)
print(U@np.diag(S)@Vt)
U, S, Vt

[[0.7066 0.0553 0.2014 ... 0.899  0.5184 0.563 ]
 [0.3057 0.0226 0.4169 ... 0.2503 0.6694 0.1826]
 [0.5715 0.7143 0.262  ... 0.1371 0.0061 0.726 ]
 ...
 [0.2873 0.564  0.5755 ... 0.5889 0.5402 0.5652]
 [0.2904 0.2841 0.6297 ... 0.0525 0.998  0.9407]
 [0.4871 0.9504 0.7749 ... 0.2592 0.6131 0.203 ]]


(array([[-0.0419, -0.0012, -0.0277, ...,  0.0045,  0.0427, -0.0471],
        [-0.0447, -0.0098,  0.0425, ...,  0.0789,  0.0076,  0.0061],
        [-0.0443, -0.0031,  0.0534, ...,  0.0543, -0.0161, -0.0024],
        ...,
        [-0.0461, -0.0369,  0.0019, ..., -0.0254, -0.0708,  0.1243],
        [-0.045 , -0.0103,  0.0583, ...,  0.0045, -0.0148,  0.007 ],
        [-0.0443, -0.0153,  0.077 , ..., -0.0367, -0.0807,  0.0056]]),
 array([2.4985e+02, 1.2625e+01, 1.2547e+01, 1.2440e+01, 1.2417e+01,
        1.2360e+01, 1.2264e+01, 1.2196e+01, 1.2191e+01, 1.2141e+01,
        1.2050e+01, 1.2032e+01, 1.1955e+01, 1.1909e+01, 1.1874e+01,
        1.1858e+01, 1.1752e+01, 1.1731e+01, 1.1694e+01, 1.1611e+01,
        1.1575e+01, 1.1544e+01, 1.1512e+01, 1.1478e+01, 1.1444e+01,
        1.1394e+01, 1.1299e+01, 1.1276e+01, 1.1248e+01, 1.1237e+01,
        1.1117e+01, 1.1086e+01, 1.1049e+01, 1.1026e+01, 1.0994e+01,
        1.0960e+01, 1.0946e+01, 1.0887e+01, 1.0869e+01, 1.0780e+01,
        1.0727e+01, 1.0679e