In [1]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [4]:
A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0],
              [2, 5, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]], dtype=np.float64).T


# A = np.array([[1, 0, 1],
#               [2, 5**.5, 0],
#               [0, 0, 1],
#               [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [5]:
print(Qt @ A @ P)

[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II
Choose the parameter phaseII as 'A', 'B1', 'B2' to test different implementations of phase II

In [2]:
%precision 4

'%.4f'

**Test SVD**

In [34]:
m = n = 10
A = np.random.rand(m,n)

In [36]:
U, S, Vt = SVD.svd(A, phaseII='B2')
# print(U@np.diag(S)@Vt)
# print(np.abs(U@np.diag(S)@Vt - A))
print("# of entrices successfully recovered by SVD with accuracy 1e-13:")
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< 1e-13))
U, S, Vt

phaseI: 0.0013196468353271484
phaseII: 0.020312786102294922
# of entrices successfully recovered by SVD with 1e-13:
100


(array([[-0.3172, -0.4538, -0.0095,  0.161 , -0.3594,  0.0897, -0.0377,
         -0.5788,  0.4332,  0.0783],
        [-0.3063,  0.0935,  0.0541,  0.628 , -0.273 ,  0.2324,  0.4242,
          0.3117, -0.1293, -0.2791],
        [-0.249 , -0.2525,  0.129 ,  0.3802,  0.6435,  0.0302, -0.1739,
         -0.2551, -0.4349,  0.1171],
        [-0.3521,  0.073 ,  0.4024, -0.1648,  0.0877, -0.2179, -0.3424,
          0.0511,  0.17  , -0.6912],
        [-0.2505,  0.0225,  0.6027, -0.1126, -0.2922,  0.1554, -0.2582,
          0.2792, -0.1263,  0.5391],
        [-0.2634,  0.4599, -0.2579,  0.1853, -0.2916, -0.596 , -0.2003,
         -0.2235, -0.2492,  0.1607],
        [-0.3511,  0.5646,  0.1075, -0.2015,  0.3336,  0.2134,  0.4054,
         -0.274 ,  0.2824,  0.1725],
        [-0.4551, -0.0584, -0.5774, -0.0461,  0.1632,  0.1902, -0.3421,
          0.4443,  0.2474,  0.1245],
        [-0.2743, -0.4103,  0.0471, -0.2196,  0.1135, -0.5819,  0.5181,
          0.2549,  0.0266,  0.1428],
        [-0.2861, -

**Scipy SVD**

In [9]:
U, S, Vt  = scipy.linalg.svd(A, full_matrices=False)
# print(np.abs(U@np.diag(S)@Vt - A))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< 1e-13))
U, S, Vt

1048576


(array([[-0.031 , -0.0079, -0.031 , ...,  0.0236, -0.0389,  0.0148],
        [-0.0307,  0.0149, -0.0027, ...,  0.0223, -0.075 , -0.0087],
        [-0.0299,  0.018 ,  0.0271, ..., -0.0546,  0.0488,  0.0285],
        ...,
        [-0.0307,  0.0122, -0.0187, ...,  0.0494,  0.0392, -0.0157],
        [-0.032 ,  0.0215,  0.0264, ..., -0.0033, -0.0158,  0.0102],
        [-0.0307, -0.0016,  0.0182, ...,  0.0572,  0.0323, -0.0378]]),
 array([5.1205e+02, 1.8386e+01, 1.8278e+01, ..., 1.8997e-02, 1.0529e-02,
        1.6051e-03]),
 array([[-0.0306, -0.0313, -0.0306, ..., -0.0316, -0.0316, -0.0309],
        [-0.0113, -0.015 , -0.0339, ...,  0.0244,  0.0364,  0.0505],
        [ 0.0049, -0.0784,  0.0272, ...,  0.0052, -0.0015, -0.0652],
        ...,
        [ 0.0169,  0.0217, -0.0281, ..., -0.0257, -0.0362,  0.0261],
        [ 0.0334, -0.0018, -0.0285, ..., -0.0341, -0.0225,  0.0613],
        [ 0.0437,  0.0073, -0.0002, ...,  0.0267, -0.0071,  0.0326]]))