In [1]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [2]:
%precision 8

'%.8f'

In [3]:
A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0],
              [2, 5, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]], dtype=np.float64).T


# A = np.array([[1, 0, 1],
#               [2, 5**.5, 0],
#               [0, 0, 1],
#               [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [4]:
print(Qt @ A @ P)

[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II-A

**Test SVD**

In [5]:
%precision 4

'%.4f'

In [6]:
m = 1024
n = 1024
A = np.random.rand(m,n)


In [7]:
U, S, Vt = SVD.svd(A)
# print(U@np.diag(S)@Vt)
# print(np.abs(U@np.diag(S)@Vt - A))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< 1e-13))
U, S, Vt

phaseI: 42.5489239692688
phaseII: 80.60454821586609
1048576


(array([[-0.0304, -0.0228,  0.0123, ...,  0.0422, -0.0239,  0.0598],
        [-0.0312, -0.0907,  0.0269, ..., -0.0023,  0.0389,  0.0111],
        [-0.032 , -0.0313, -0.0285, ...,  0.019 , -0.0345,  0.0039],
        ...,
        [-0.0316, -0.0093,  0.0017, ..., -0.0268,  0.0236,  0.0415],
        [-0.0312, -0.0009, -0.0135, ..., -0.0367,  0.0471,  0.0342],
        [-0.0315, -0.0397, -0.012 , ..., -0.0266, -0.0393, -0.0117]]),
 array([5.1228e+02, 1.8417e+01, 1.8282e+01, ..., 2.6306e-02, 1.8454e-02,
        7.8197e-04]),
 array([[-0.0312, -0.0319, -0.0322, ..., -0.0308, -0.0316, -0.0321],
        [ 0.0436,  0.0134,  0.0366, ...,  0.0112,  0.042 , -0.024 ],
        [ 0.0079,  0.1219,  0.0588, ..., -0.0068, -0.055 ,  0.0174],
        ...,
        [-0.0125,  0.0177,  0.0294, ..., -0.009 ,  0.0309,  0.0069],
        [ 0.018 ,  0.0115,  0.0331, ..., -0.0364, -0.0044,  0.0103],
        [ 0.0105, -0.0026, -0.0109, ...,  0.0131, -0.0201, -0.0224]]))

In [8]:
U, S, Vt  = scipy.linalg.svd(A, full_matrices=False)
# print(np.abs(U@np.diag(S)@Vt - A))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< 1e-13))
U, S, Vt

1048576


(array([[-0.0304, -0.0228, -0.0123, ...,  0.0422,  0.0239, -0.0598],
        [-0.0312, -0.0907, -0.0269, ..., -0.0023, -0.0389, -0.0111],
        [-0.032 , -0.0313,  0.0285, ...,  0.019 ,  0.0345, -0.0039],
        ...,
        [-0.0316, -0.0093, -0.0017, ..., -0.0268, -0.0236, -0.0415],
        [-0.0312, -0.0009,  0.0135, ..., -0.0367, -0.0471, -0.0342],
        [-0.0315, -0.0397,  0.012 , ..., -0.0266,  0.0393,  0.0117]]),
 array([5.1228e+02, 1.8417e+01, 1.8282e+01, ..., 2.6306e-02, 1.8454e-02,
        7.8197e-04]),
 array([[-0.0312, -0.0319, -0.0322, ..., -0.0308, -0.0316, -0.0321],
        [ 0.0436,  0.0134,  0.0366, ...,  0.0112,  0.042 , -0.024 ],
        [-0.0079, -0.1219, -0.0588, ...,  0.0068,  0.055 , -0.0174],
        ...,
        [-0.0125,  0.0177,  0.0294, ..., -0.009 ,  0.0309,  0.0069],
        [-0.018 , -0.0115, -0.0331, ...,  0.0364,  0.0044, -0.0103],
        [-0.0105,  0.0026,  0.0109, ..., -0.0131,  0.0201,  0.0224]]))