In [46]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [47]:
A = np.array([[0, 0, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0],
              [2, 5, 0, 0],
              [0, 0, 0, 0],
              [0, 0, 0, 0]], dtype=np.float64).T


# A = np.array([[1, 0, 1],
#               [2, 5**.5, 0],
#               [0, 0, 1],
#               [0, 0, 1]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


In [48]:
print(Qt @ A @ P)

[[ 2.  0.  0.  0.  0.  0.  0.]
 [-5.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]


## Phase-II
Choose the parameter phaseII as 'A', 'B1', 'B2' to test different implementations of phase II

**Test SVD**

In [51]:
m = n = 1024
A = np.random.rand(m,n)

In [52]:
U, S, Vt = SVD.svd(A, phaseII='B1')
# U, S, Vt = SVD.svd(A, eigen=scipy.linalg.eigh)

# print(U@np.diag(S)@Vt)
# print(np.abs(U@np.diag(S)@Vt - A))
# acc = 1e-15
# print("# of entrices successfully recovered by SVD with accuracy:{}".format(acc))
# print(np.sum(np.abs(U@np.diag(S)@Vt - A)< acc))
# U, S, Vt

phaseI: 31.802248239517212
phaseII: 24.811877965927124


**Accuracy Test:**

In [56]:
acc = 1e-13
print("Percentage of entrices successfully recovered by SVD with accuracy: {}".format(acc))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< acc) / (n*m) * 100, "%")

Percentage of entrices successfully recovered by SVD with accuracy:1e-13
100.0 %


**Scipy SVD**

In [57]:
U, S, Vt  = scipy.linalg.svd(A, full_matrices=False)
# print(np.abs(U@np.diag(S)@Vt - A))
acc = 1e-13
print("Percentage of entrices successfully recovered by SVD with accuracy: {}".format(acc))
print(np.sum(np.abs(U@np.diag(S)@Vt - A)< acc) / (n*m) * 100, "%")
# U, S, Vt

Percentage of entrices successfully recovered by SVD with accuracy: 1e-13
100.0 %
