In [105]:
import numpy as np
import scipy
import utils
from utils import HouseHolder, QR, SVD

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Problem 1: SVD by Two-Phase Approach

## Phase-I: Golub-Kahan Bidiagonalization

In [106]:
A = np.array([[1, 0, 1],
              [0, 0, 0],
              [2, 5**.5, 0],
              [0, 0, 0],
              [0, 0, 0]])
B, Qt, P = SVD.svd_phaseI(A)
print(B)


[[-2.23606798e+00  2.04939015e+00 -9.45175510e-17]
 [ 0.00000000e+00  7.80720058e-01 -1.09108945e+00]
 [ 1.11022302e-16  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]
 [ 0.00000000e+00  0.00000000e+00             nan]]


In [107]:
P.shape

(3, 3)

In [108]:
Qt @ A @ P

array([[-2.23606798e+00,  2.04939015e+00,  9.45175510e-17],
       [-1.11022302e-16,  7.80720058e-01, -1.09108945e+00],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan]])

Todo: We may not need to form the reflection matrix H explicitly during Golub-Kahan bidiagonalization.

## Phase-II-A

In [110]:
scipy.linalg.eigh(A)

ValueError: expected square "a" matrix

**Test SVD**

In [ ]:
%precision 8

'%.8f'

In [112]:
SVD.svd(A)

ValueError: array must not contain infs or NaNs

In [113]:
scipy.linalg.svd(A, full_matrices=False)

(array([[-0.25666794,  0.96649965,  0.        ],
        [ 0.        ,  0.        , -1.        ],
        [-0.96649965, -0.25666794,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]]),
 array([3.08725264, 1.21196994, 0.        ]),
 array([[-0.70926079, -0.70002658, -0.08313798],
        [ 0.37390678, -0.47354883,  0.79746174],
        [-0.5976143 ,  0.53452248,  0.5976143 ]]))