In [13]:
import numpy as np
A = np.array([[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 1]])
A1 = np.array([[1, 1, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
A2 = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 1], [0, 0, 0, 1]])
Q1 = np.array([[0.6, 0.8, 0, 0], [-0.8, 0.6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
Q2 = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0.6, 0.8], [0, 0, -0.8, 0.6]])
print(Q1 @ A1 @ Q1.T @ Q2 @ A2 @Q2.T)
print(Q1 @ Q2 @ A1 @ A2 @ Q2.T @ Q1.T)
print(Q1 @ Q2)
print(Q2 @ Q1)

[[ 1.48  0.36  0.    0.  ]
 [-0.64  0.52  0.    0.  ]
 [ 0.    0.    1.48  0.36]
 [ 0.    0.   -0.64  0.52]]
[[ 1.48  0.36  0.    0.  ]
 [-0.64  0.52  0.    0.  ]
 [ 0.    0.    1.48  0.36]
 [ 0.    0.   -0.64  0.52]]
[[ 0.6  0.8  0.   0. ]
 [-0.8  0.6  0.   0. ]
 [ 0.   0.   0.6  0.8]
 [ 0.   0.  -0.8  0.6]]
[[ 0.6  0.8  0.   0. ]
 [-0.8  0.6  0.   0. ]
 [ 0.   0.   0.6  0.8]
 [ 0.   0.  -0.8  0.6]]
